apiVersion: apps/v1
kind: Deployment
metadata:
  name: humangov-python-app-sao-paulo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: humangov-python-app-sao-paulo
  template:
    metadata:
      labels:
        app: humangov-python-app-sao-paulo
    spec:
      serviceAccountName: humangov-pod-execution-role
      containers:
      - name: humangov-python-app-sao-paulo
        image: public.ecr.aws/k5z6r9x6/humangov-app:latest
        env:
        - name: AWS_BUCKET
          value: "humangov-sao-paulo-s3-u9hr"
        - name: AWS_DYNAMODB_TABLE
          value: "humangov-sao-paulo-dynamodb"
        - name: AWS_REGION
          value: "us-east-1"
        - name: US_STATE
          value: "sao-paulo"

---

apiVersion: v1
kind: Service
metadata:
  name: humangov-python-app-service-sao-paulo
spec:
  type: ClusterIP
  selector:
    app: humangov-python-app-sao-paulo
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: humangov-nginx-reverse-proxy-sao-paulo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: humangov-nginx-reverse-proxy-sao-paulo
  template:
    metadata:
      labels:
        app: humangov-nginx-reverse-proxy-sao-paulo
    spec:
      containers:
      - name: humangov-nginx-reverse-proxy-sao-paulo
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: humangov-nginx-config-sao-paulo-vol
          mountPath: /etc/nginx/
      volumes:
      - name: humangov-nginx-config-sao-paulo-vol
        configMap:
          name: humangov-nginx-config-sao-paulo

---

apiVersion: v1
kind: Service
metadata:
  name: humangov-nginx-service-sao-paulo
spec:
  selector:
    app: humangov-nginx-reverse-proxy-sao-paulo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: humangov-nginx-config-sao-paulo
data:
  nginx.conf: |

    events {
      worker_connections 1024;
    }

    http {

      server {
        listen 80;

        location / {
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_pass http://humangov-python-app-service-sao-paulo:8000; # App container
        }
      }
    }
  
  proxy_params: |
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;